#!/bin/bash

if [[ -f ./vendor/river2D/clean ]]
then
    pushd ./vendor/river2D > /dev/null
    ./clean
    popd > /dev/null
fi

echo -e "\033[33mcleaning up mapedit builds...\033[0m"

if [[ -d ./build/ ]]
then
    rm ./build/ -rf
fi

if [[ -d ./bin/ ]]
then
    rm ./bin/ -rf
fi

if [[ -d ./build/ ]]
then
    rm ./build/ -rf
fi

echo -e "\033[32mcleaned mapedit!\n\033[0m"
