#!/bin/bash

# BACKLOG: switch to writing makefiles and hand-write compile commands

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

if [[ $1 = "" ]]
then
    build="release"
else
    build=$1
fi

if [[ $build = "asan" ]] || [[ $build = "debug" ]] || [[ $build = "release" ]]
then

    if [[ -f "./vendor/river2D/run" ]]
    then
        pushd ./vendor/river2D/ > /dev/null
        ./run $build --compile-only
        if [[ $? != 0 ]]
        then
            echo -e "\033[31m\nERROR: failed to compile river2D.\033[0m"
            exit -1
        fi
        popd > /dev/null
    else
        echo -e "\033[31m\nERROR: can't find river2D's run script.\033[0m"
    fi

    echo ""
    echo -e "\033[36mcompiling river2D...\033[0m"
    echo ""
    premake5 ecc
    premake5 gmake

    pushd ./build/ > /dev/null
    make config=$build\_linux
else
    echo -e "\033[31m\nERROR: invalid make config: $build.\033[0m"
    exit -2;
fi

if [[ $? != 0 ]]
then
    echo -e "\033[31m\nERROR: failed to compile mapedit.\n\033[0m"
    exit -1
fi

echo -e "\n"

if [[ $2 = "--compile-only" ]]
then
    exit 0
fi

popd > /dev/null

chmod +x ./bin/$build/mapedit
./bin/$build/mapedit
