#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

compile_imgsurf()
{
    if [[ -f "./vendor/imgsurf/run" ]]
    then
        pushd ./vendor/imgsurf/ > /dev/null
        ./run $1 --compile-only
        if [[ $? != 0 ]]
        then
            exit -1
        fi
        popd > /dev/null
    else
        echo -e "\033[31mERROR: can't find imgsurf's run script.\033[0m"
    fi
}

compileprep()
{
    echo ""
    echo -e "\033[36mcompiling river2D...\033[0m"
    echo ""
    premake5 ecc
    premake5 gmake
}

if [[ $1 = "debug" ]]
then
    compile_imgsurf $1
    compileprep
    pushd ./build/ > /dev/null
    make config=debug_linux
elif [[ $1 = "release" ]]
then
    compile_imgsurf $1
    compileprep
    pushd ./build/ > /dev/null
    make config=release_linux
elif [[ $1 = "asan" ]]
then
    compile_imgsurf $1
    compileprep
    pushd ./build/ > /dev/null
    make config=asan_linux
else
    echo -e "\033[31m\nERROR: invalid make config: $1.\033[0m"
    exit -2;
fi

if [[ $? != 0 ]]
then
    echo -e "\033[31m\nERROR: failed to compile.\n\033[0m"
    exit -1
fi

echo -e "\n"

if [[ $2 = "--compile-only" ]]
then
    exit 0
fi

popd > /dev/null

chmod +x ./bin/$1/river2Dmapedit
./bin/$1/river2Dmapedit
